# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# linjinbin
gems:         [jekyll-paginate]

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: 9leg
description: java技术文章
keywords: Java
url: http://9leg.com
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: zhujiajun
    email: zhujiajun.me@gmail.com
    imageLink: /images/header.jpg
    simpleIntro: I Have a Dream
    detailIntro:
      <p>高中时期天赋技能选错,接触了电脑编程,一发不可收拾,成了程序员一枚.</p>
      <p>主要使用Java,会一点Android,正在学习Scala.</p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: https://github.com/zJiaJun/
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: https://plus.google.com/116595571760191938657/about

#Links
customLinks:
  - item:
    - text: 技术小黑屋
      url: http://droidyue.com/
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends    
  - item:
    - text: Java Code Geeks
      url: http://www.javacodegeeks.com/
    - text: Web Developer
      url: http://www.fromdev.com/
    - text: BeginnersBook
      url: http://beginnersbook.com/
    - text: Mkyong
      url: http://www.mkyong.com/
    - text: Java By Nataraj
      url: http://javabynataraj.blogspot.in/
    message: About Java

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-58146229-1

#baidu tongji
baiduTongji:
  config: true
  #id: c12b560f0372d5995701449b9eac606c
  id:  9144251ce5a4f4019de4bc601b9b490b

#comment config
disqus:
  config: true
  id: handong1587

duoshuo:
  config: false
  id: null

#baidu share config
baiduShare:
  config: false
  